### ISSUE TITLE
Error with WorldEdit 7.2.10 (1.18.2)

### ISSUE THREAD

**Issue by pavog** [JuicyLdoin/MineCreator#1]
Hi, I'm running the latest version of MineCreator (1.5.4), WorldEdit 7.2.10 and a Paper 1.18.2 server.
I selected a region with worldedit and executed this command: /minecreator create mine cuboid

The following error occured:

```
[10:42:20] [Server thread/INFO]: EvilCodes issued server command: /minecreator create mine cuboid
--
187 | [10:42:20] [Server thread/ERROR]: null
188 | org.bukkit.command.CommandException: Unhandled exception executing command 'minecreator' in plugin MineCreator v1.5.4
189 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
190 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
191 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-333]
192 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
193 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
194 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
195 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
196 | at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
197 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
198 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-333]
199 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
200 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
201 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-333]
202 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-333]
203 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
204 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-333]
205 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-333]
206 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
207 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-333]
208 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-333]
209 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
210 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
211 | Caused by: java.lang.NoSuchMethodError: 'com.sk89q.worldedit.Vector com.sk89q.worldedit.regions.Region.getMinimumPoint()'
212 | at ua.ldoin.minecreator.Commands.onCommand(Commands.java:119) ~[MineCreator.jar:?]
213 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
214 | ... 21 more
```

**Comment by JuicyLdoin** [comment]
Hey I tested it on my local server and I don't get any errors...

**Comment by JuicyLdoin** [comment]
Fixed in new update.
